os: linux
dist: bionic
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"

install:
        - export INSTALL_DIR=/opt/symbiflow
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b -p $INSTALL_DIR/conda && rm Miniconda3-latest-Linux-x86_64.sh
        - source $INSTALL_DIR/conda/etc/profile.d/conda.sh
        - conda update -y -q conda
        - wget -qO- https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/4/20200416-002215/symbiflow-arch-defs-install-a321d9d9.tar.xz | tar -xJ -C $INSTALL_DIR
        - conda install -y -c symbiflow yosys yosys-plugins vtr-no-gui
        - conda install -y make lxml simplejson intervaltree git pip
        - conda activate
        - pip install python-constraint
        - pip install git+https://github.com/symbiflow/fasm
        - conda deactivate

script:
        - export INSTALL_DIR=/opt/symbiflow
        - # adding symbiflow toolchain binaries to PATH
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - source $INSTALL_DIR/conda/etc/profile.d/conda.sh
        - conda activate
        - git clone https://github.com/SymbiFlow/symbiflow-examples && cd symbiflow-examples
        - # counter example
        - pushd counter_test/arty && make && popd
        - pushd counter_test/basys3 && make && popd
        - # picosoc example
        - pushd picosoc_demo && make && popd
        - # litex example
        - pushd linux_litex_demo && make && popd
