os: linux
dist: bionic
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
       - INSTALL_DIR: /opt/quicklogic
addons:
  apt:
    packages:
        - wget
        - locales

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"

install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $INSTALL_DIR/miniconda && rm miniconda.sh
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda config --add channels conda-forge
        - conda config --add channels antmicro/label/ql
        - conda activate
        - conda install -c antmicro/label/ql yosys
        - conda install -c antmicro/label/ql yosys-plugins
        - conda install -c antmicro/label/ql vtr
        - conda install lxml simplejson intervaltree python-constraint git pip
        - pip install git+https://github.com/symbiflow/fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm-utils
        - conda deactivate

script:
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - tar -xf arch-defs-install.tar.xz -C $INSTALL_DIR
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - conda activate
        - pushd quicklogic_demo && make && popd
