os: linux
dist: bionic
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales

stages:
    - xc7
    - quicklogic

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

jobs:
  include:
    - stage: quicklogic
      env:
        - INSTALL_DIR: /opt/symbiflow/quicklogic
      install:
        - bash miniconda.sh -b -p $INSTALL_DIR/miniconda && rm miniconda.sh
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - conda update -q conda
        - conda install -c antmicro/label/ql yosys
        - conda install -c antmicro/label/ql yosys-plugins
        - conda install -c symbiflow vtr-no-gui
        - conda install -y make lxml simplejson intervaltree git pip
        - conda activate
        - pip install python-constraint
        - pip install git+https://github.com/symbiflow/fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm-utils
        - conda deactivate
      script:
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - tar -xf arch-defs-install.tar.xz -C $INSTALL_DIR
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - conda activate
        - pushd quicklogic && make && popd
