os: linux
dist: bionic
language: c++
env:
  global:
       - DEBIAN_FRONTEND: noninteractive
addons:
  apt:
    packages:
        - wget
        - locales

stages:
    - xc7
    - quicklogic

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

jobs:
  include:
    - stage: xc7
      env:
        - INSTALL_DIR: /opt/symbiflow/xc7
      install:
        - bash miniconda.sh -b -p $INSTALL_DIR/miniconda && rm miniconda.sh
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda config --add channels conda-forge
        - conda config --add channels symbiflow
        - conda activate
        - conda install -c symbiflow yosys
        - conda install -c symbiflow yosys-plugins
        - conda install -c symbiflow vtr=8.0.0.rc2_3575_g253f75b6d
        - conda install lxml simplejson intervaltree python-constraint git pip
        - pip install git+https://github.com/symbiflow/fasm
        - wget "https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/4/20200416-002215/symbiflow-arch-defs-install-a321d9d9.tar.xz"
        - conda deactivate
      script:
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - tar -xf symbiflow-arch-defs-install-a321d9d9.tar.xz -C $INSTALL_DIR
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - conda activate
        - pushd xc7/counter_test/arty && make && popd
        - pushd xc7/counter_test/basys3 && make && popd
        - pushd xc7/picosoc_demo && make && popd
        - pushd xc7/linux_litex_demo && make && popd

    - stage: quicklogic
      env:
        - INSTALL_DIR: /opt/symbiflow/quicklogic
      install:
        - bash miniconda.sh -b -p $INSTALL_DIR/miniconda && rm miniconda.sh
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda config --add channels conda-forge
        - conda config --add channels antmicro/label/ql
        - conda activate
        - conda install -c antmicro/label/ql yosys
        - conda install -c antmicro/label/ql yosys-plugins
        - conda install -c antmicro/label/ql vtr
        - conda install lxml simplejson intervaltree python-constraint git pip
        - pip install git+https://github.com/symbiflow/fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm
        - pip install git+https://github.com/antmicro/quicklogic-fasm-utils
        - conda deactivate
      script:
        - source "$INSTALL_DIR/miniconda/etc/profile.d/conda.sh"
        - tar -xf arch-defs-install.tar.xz -C $INSTALL_DIR
        - export PATH=$INSTALL_DIR/install/bin:$PATH
        - conda activate
        - pushd quicklogic_demo && make && popd
